export const APP_ROUTES = {
  login: '/login',
  register: '/register',
  forbidden: '/403',
  notFound: '/404',
  admin: {
    dashboard: '/admin/dashboard',
    users: '/admin/users',
    examSessions: '/admin/exam-sessions',
    subjects: '/admin/subjects',
    subjectAssignments: '/admin/subject-assignments',
    settings: '/admin/settings',
  },
  lecturer: {
    dashboard: '/lecturer/dashboard',
    questions: '/lecturer/questions',
    questionCreate: '/lecturer/questions/create',
    questionDetail: '/lecturer/questions/:id',
    questionsImport: '/lecturer/questions/import',
    questionsGenerate: '/lecturer/questions/generate',
    rubrics: '/lecturer/rubrics',
    exams: '/lecturer/exams',
    examCreate: '/lecturer/exams/create',
    examDetail: '/lecturer/exams/:id',
    examSchedule: '/lecturer/exams/:id/schedule',
    examParticipants: '/lecturer/exams/:id/participants',
    evaluations: '/lecturer/evaluations',
    evaluationDetail: '/lecturer/evaluations/:id',
    monitoring: '/lecturer/monitoring',
    reports: '/lecturer/reports',
  },
  student: {
    dashboard: '/student/dashboard',
    exams: '/student/exams',
    examDetail: '/student/exams/:id',
    interview: '/student/interview/:id',
    reports: '/student/reports/:id',
  },
} as const;
